"""empty message

Revision ID: 30534822f02e
Revises: a300b1d1e6f0
Create Date: 2024-10-31 20:13:51.976458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30534822f02e'
down_revision = 'a300b1d1e6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=False))
        batch_op.drop_column('autor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
